// spike-probe: runs INSIDE the plugin sandbox as a build command.
// Answers, empirically, for the invoking target:
//   (a) can it read the *source files* of a dependency target?
//   (b) what do the sandbox rules actually permit (reads/writes)?
//   (c) can it see a dependency target's *generated* plugin output?
// Results are baked into a generated Swift file the App prints at runtime.

import Foundation

struct Payload: Codable {
    let targetName: String
    let ownSources: [String]
    let dependencySources: [String]
    let siblingGeneratedGuesses: [String]
    let outsideWriteProbe: String
    let outsideReadProbe: String
    let output: String
}

guard CommandLine.arguments.count == 2,
      let data = FileManager.default.contents(atPath: CommandLine.arguments[1]),
      let payload = try? JSONDecoder().decode(Payload.self, from: data)
else {
    FileHandle.standardError.write(Data("spike-probe: bad payload\n".utf8))
    exit(2)
}

var report: [String] = ["== spike-probe report for target \(payload.targetName) =="]

// (a) Cross-target SOURCE visibility
for path in payload.dependencySources {
    do {
        let text = try String(contentsOfFile: path, encoding: .utf8)
        let marker = text.contains("@Component") ? "marker FOUND" : "marker missing"
        report.append("(a) READ OK  dependency source \(path) — \(marker)")
    } catch {
        report.append("(a) READ FAILED dependency source \(path): \(error)")
    }
}
if payload.dependencySources.isEmpty {
    report.append("(a) no dependency sources passed (this is the leaf target)")
}

// (b) Sandbox: read outside the package
do {
    _ = try String(contentsOfFile: payload.outsideReadProbe, encoding: .utf8)
    report.append("(b) READ OK  outside path \(payload.outsideReadProbe) (sandbox permits file reads)")
} catch {
    report.append("(b) READ DENIED outside path \(payload.outsideReadProbe): \(error)")
}

// (b) Sandbox: write outside the plugin work directory
do {
    try "escape attempt".write(toFile: payload.outsideWriteProbe, atomically: true, encoding: .utf8)
    report.append("(b) WRITE UNEXPECTEDLY SUCCEEDED at \(payload.outsideWriteProbe) — sandbox weaker than documented!")
    try? FileManager.default.removeItem(atPath: payload.outsideWriteProbe)
} catch {
    report.append("(b) WRITE DENIED outside work dir at \(payload.outsideWriteProbe) (expected)")
}

// (c) Dependency target's generated output visibility
for guess in payload.siblingGeneratedGuesses {
    if FileManager.default.fileExists(atPath: guess) {
        report.append("(c) sibling generated output VISIBLE at \(guess)")
    } else {
        report.append("(c) sibling generated output NOT visible at \(guess) (expected — per-target work dirs)")
    }
}

// Emit the generated file. Also demonstrates writes to the plugin work
// directory succeed (the permitted half of (b)).
let escaped = report.joined(separator: "\n")
    .replacingOccurrences(of: "\\", with: "\\\\")
    .replacingOccurrences(of: "\"", with: "\\\"")

let generated = """
// AUTO-GENERATED by spike-probe — do not edit.
public enum SpikeReport_\(payload.targetName.replacingOccurrences(of: "-", with: "_")) {
    public static let text: String = \"\"\"
\(escaped)
\"\"\"
}
"""

do {
    try generated.write(toFile: payload.output, atomically: true, encoding: .utf8)
} catch {
    FileHandle.standardError.write(Data("spike-probe: cannot write output: \(error)\n".utf8))
    exit(2)
}
